networks:
  caddy:
    external: true
services:
  web:
    image: wpatiphan/react-demo
    container_name: react
    ports:
      - 3000:3000
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - caddy
