name: Deploy React GA
on:
  push:
  workflow_dispatch:
jobs:
  lint:
    # bun run lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v5
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8
      - name: Install deps
        run: bun i
      - name: lint
        run: bun run lint
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v5
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8
      - name: Install deps
        run: bun i'
      - name: Build
        run: bun run build
      - name: List dist/
        run: ls dist
      - name: Deploy
        run: echo "Deploying..."
