name: Deploy React GA
on:
  push:
  #   branches:
  #     - main
  workflow_dispatch:
  pull_request:
    types:
      - opened
# env:
#   BUN_VERSION: 1.2.8
jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    container:
      image: oven/bun:1
      env:
        NODE_ENV: production
    steps:
      - name: Install And Cache
        uses: .github/actions/install-cache
      - name: Build
        run: bun run build
      - name: List dist/
        run: ls dist
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/
  deploy:
    if: success()
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: dist
      - name: Deploy
        run: echo "Deploying..."
  notify-success:
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy
    if: success()
    steps:
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "🟢 Success, Commit ${{ github.sha }} has been deployed."
  notify-failure:
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy
    if: failure()
    steps:
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "❌ Fail, Commit ${{ github.sha }} not deploy."
