name: Matrix
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun_version: [1.2.0, 1.2.8, 1.2.22]
        browser: ["firefox", "chrome", "safari"]
    steps:
      - name: Print Bun Version and Test browser
        run: echo '${{ matrix.bun_version }} - ${{ matrix.browser }}'
